### PR TITLE
InputField: error state if max length exceeded

### PR DESCRIPTION
**Pull request by lewisrenfrew**
- Doesn't truncate, just gets all shouty if max length exceeded

Screenshot 2022-11-02 160806

### CODE REVIEW

**Comment by lewisrenfrew** [comment]
this pr looks big cos I did a big tidy. The InputField and its test are the only real changes

**Comment by RossStewart** [comment]
> this pr looks big cos I did a big tidy. The InputField and its test are the only real changes

Just saw the number of files changed and gulped haha. Reading it all over now.

**Review by richardiphillips — APPROVED** [review]
lks good. 
Did you decide against the (lowercase) standalone inputProps = {{etc}}?
Is that just an internet red herring?

**Comment by lewisrenfrew** [comment]
> lks good. Did you decide against the (lowercase) standalone inputProps = {{etc}}? Is that just an internet red herring?

I didn't want to actually pass maxLength to the underlying < input > - so no inputProps. if you do then itjust makes it silently truncate whatever you type in which I feel could be a bit frustrating

**Pull request merged**
